# Generated by Django 4.2.7 on 2025-11-15 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("county", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        max_length=20,
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("contact_phone", models.CharField(max_length=15)),
                (
                    "is_partner",
                    models.BooleanField(
                        default=False,
                        help_text="Partner schools get additional features",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "School",
                "verbose_name_plural": "Schools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=15, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "grade_level",
                    models.IntegerField(
                        choices=[
                            (1, "Grade 1"),
                            (2, "Grade 2"),
                            (3, "Grade 3"),
                            (4, "Grade 4"),
                            (5, "Grade 5"),
                            (6, "Grade 6"),
                            (7, "Grade 7"),
                            (8, "Grade 8"),
                        ]
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "preferred_channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("ussd", "USSD"), ("app", "App")],
                        default="sms",
                        max_length=10,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("sw", "Swahili")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User preferences and custom settings",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="students.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="parents", to="students.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("channel", models.CharField(max_length=10)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of events/actions during this session",
                    ),
                ),
                (
                    "state",
                    models.JSONField(
                        default=dict,
                        help_text="Session state data (current lesson, progress, etc.)",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Session",
                "verbose_name_plural": "Student Sessions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-started_at"],
                        name="students_st_student_93bde5_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["phone_number"], name="students_st_phone_n_97f681_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["grade_level"], name="students_st_grade_l_30e3b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "grade_level"], name="students_st_school__6cc7ce_idx"
            ),
        ),
    ]
