# Generated by Django 4.2.7 on 2025-11-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="subscription_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("basic", "Basic"), ("premium", "Premium")],
                default="free",
                help_text="Subscription tier for SMS quotas",
                max_length=20,
            ),
        ),
    ]
