# Generated by Django 4.2.7 on 2025-11-15 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Phone number in E.164 format (e.g., +254712345678)",
                        max_length=15,
                    ),
                ),
                (
                    "otp_code",
                    models.CharField(help_text="6-digit OTP code", max_length=6),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this OTP has been successfully verified",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="OTP expiration time (5 minutes from creation)"
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of verification attempts made"
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3, help_text="Maximum allowed verification attempts"
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Verification",
                "verbose_name_plural": "OTP Verifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "-created_at"],
                        name="authenticat_phone_n_d99cfd_idx",
                    )
                ],
            },
        ),
    ]
