# Generated by Django 4.2.7 on 2025-11-15 21:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0002_student_subscription_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.JSONField(
                        default=dict,
                        help_text="Session state: current_lesson, current_question_index, waiting_for_answer, etc.",
                    ),
                ),
                ("message_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_sessions",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Session",
                "verbose_name_plural": "SMS Sessions",
                "ordering": ["-last_activity"],
                "indexes": [
                    models.Index(
                        fields=["student", "-last_activity"],
                        name="channels_sm_student_aab93d_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="channels_sm_is_acti_8586ad_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SMSMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=15)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost in KES",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID from Africa's Talking",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated student (if identified)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_messages",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Message",
                "verbose_name_plural": "SMS Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "-created_at"],
                        name="channels_sm_phone_n_b62a10_idx",
                    ),
                    models.Index(
                        fields=["student", "-created_at"],
                        name="channels_sm_student_b93810_idx",
                    ),
                    models.Index(
                        fields=["status"], name="channels_sm_status_65ddee_idx"
                    ),
                ],
            },
        ),
    ]
