# Generated by Django 4.2.7 on 2025-11-15 21:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Fractions, Verbs", max_length=200
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., MATH_FRAC_G4", max_length=50, unique=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "grade_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ]
                    ),
                ),
                (
                    "learning_objectives",
                    models.JSONField(
                        default=list,
                        help_text="List of learning objectives for this concept",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prerequisites",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Concepts that should be learned before this one",
                        related_name="dependent_concepts",
                        to="content.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concept",
                "verbose_name_plural": "Concepts",
                "ordering": ["grade_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "difficulty_level",
                    models.IntegerField(
                        help_text="1=Very Easy, 5=Very Hard",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("video", "Video"),
                            ("interactive", "Interactive"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text='Structured content: {"introduction": "", "explanation": "", "examples": []}'
                    ),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        help_text="Estimated time in seconds to complete this lesson"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order within the concept"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="content.concept",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
                "ordering": ["concept", "order"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Mathematics, English", max_length=100
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g., MATH, ENG", max_length=20, unique=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "grade_levels",
                    models.JSONField(
                        default=list,
                        help_text="List of grade levels (1-8) this subject is taught",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ConceptMastery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mastery_level",
                    models.FloatField(
                        default=0,
                        help_text="Mastery level as percentage (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("attempts_count", models.IntegerField(default=0)),
                ("last_practiced", models.DateTimeField(blank=True, null=True)),
                (
                    "next_review_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Suggested date for next review (spaced repetition)",
                        null=True,
                    ),
                ),
                (
                    "spaced_repetition_box",
                    models.IntegerField(
                        default=1,
                        help_text="Leitner box number for spaced repetition (1-6)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_masteries",
                        to="content.concept",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concept_masteries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Concept Mastery",
                "verbose_name_plural": "Concept Masteries",
                "ordering": ["-mastery_level"],
            },
        ),
        migrations.AddField(
            model_name="concept",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="concepts",
                to="content.subject",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("fill_blank", "Fill in the Blank"),
                            ("true_false", "True/False"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='For MCQ: {"A": "option 1", "B": "option 2", ...}',
                    ),
                ),
                (
                    "correct_answer",
                    models.JSONField(
                        help_text='Single value like "A" or list for multiple correct answers ["A", "C"]'
                    ),
                ),
                (
                    "explanation",
                    models.TextField(help_text="Explanation of the correct answer"),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "media_url",
                    models.URLField(
                        blank=True, help_text="Optional image/video URL", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="content.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["lesson", "order"],
                "indexes": [
                    models.Index(
                        fields=["lesson", "order"],
                        name="content_que_lesson__edfe30_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(help_text="sms, ussd, or app", max_length=10),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answers",
                    models.JSONField(
                        default=list,
                        help_text='[{"question_id": "...", "answer": "A", "correct": true}, ...]',
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        help_text="Score as percentage (0-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "time_spent",
                    models.IntegerField(
                        blank=True, help_text="Time spent in seconds", null=True
                    ),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="content.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_attempts",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lesson Attempt",
                "verbose_name_plural": "Lesson Attempts",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-started_at"],
                        name="content_les_student_a11e98_idx",
                    ),
                    models.Index(
                        fields=["lesson", "-started_at"],
                        name="content_les_lesson__6b6600_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["concept", "order"], name="content_les_concept_8390f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["is_published"], name="content_les_is_publ_6c24a8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lesson",
            unique_together={("concept", "order")},
        ),
        migrations.AddIndex(
            model_name="conceptmastery",
            index=models.Index(
                fields=["student", "-mastery_level"],
                name="content_con_student_d69f03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conceptmastery",
            index=models.Index(
                fields=["next_review_date"], name="content_con_next_re_93952f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conceptmastery",
            unique_together={("student", "concept")},
        ),
        migrations.AddIndex(
            model_name="concept",
            index=models.Index(
                fields=["subject", "grade_level"], name="content_con_subject_54ee06_idx"
            ),
        ),
    ]
